# Welcome to Jekyll!
#

# Site settings
title: CodeAndCandlesticks
email: luispe at gmail.com
description: >-
  Explore the intersection of technology and trading at CodeAndCandlesticks. Dive into my journey as a software developer and trader, showcasing custom tools, and trading strategies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codeandcandlesticks.com" # the base hostname & protocol for your site

# Social Media Settings
github_username:  luispic2021
github_organization: CodeAndCandlesticks
linkedin_url: https://www.linkedin.com/in/luispic/
instagram_url: https://www.instagram.com/tsl_trader

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
